version: 2
jobs:
    build:
        working_directory: ~/ftps
        docker:
            - image: jcollado/ftps-ci:0.1
        parallelism: 3
        steps:
            - checkout
            - run: |
                set -e
                case $CIRCLE_NODE_INDEX in
                0)
                    tox -e py27
                    ;;
                1)
                    tox -e py35
                    ;;
                2)
                    tox -e flake8
                    ;;
                esac
